// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooShop.Infrastructure;

#nullable disable

namespace ZooShop.Infrastructure.Migrations
{
    [DbContext(typeof(ZooShopContext))]
    partial class ZooShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooShop.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            FullName = "Іван Петренко",
                            LoyaltyPoints = 100,
                            PhoneNumber = "+380501234567"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FullName = "Марія Коваленко",
                            LoyaltyPoints = 250,
                            PhoneNumber = "+380502345678"
                        });
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.CustomerProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredPaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Київ, вул. Хрещатик, 1",
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivan.petrenko@example.com",
                            PreferredPaymentMethod = "Карта"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Львів, пр. Свободи, 10",
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.kovalenko@example.com",
                            PreferredPaymentMethod = "Готівка"
                        });
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.OrderProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("PriceAtOrder")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId");

                    b.ToTable("OrderProductes");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<double>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.PetFoodModel", b =>
                {
                    b.HasBaseType("ZooShop.Infrastructure.Models.ProductModel");

                    b.Property<string>("DoughType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ExtraCheese")
                        .HasColumnType("boolean");

                    b.Property<int>("SizeCm")
                        .HasColumnType("integer");

                    b.Property<string>("Toppings")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("PetProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Класична піца з томатами та моцарелою",
                            IsAvailable = true,
                            Name = "Маргарита",
                            Price = 180.0,
                            DoughType = "Тонке тісто",
                            ExtraCheese = false,
                            SizeCm = 30,
                            Toppings = "Томати, моцарела, базилік"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Піца з пепероні та сиром",
                            IsAvailable = true,
                            Name = "Пепероні",
                            Price = 220.0,
                            DoughType = "Традиційне тісто",
                            ExtraCheese = true,
                            SizeCm = 35,
                            Toppings = "Пепероні, моцарела, томатний соус"
                        });
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.AccessoryModel", b =>
                {
                    b.HasBaseType("ZooShop.Infrastructure.Models.ProductModel");

                    b.Property<int>("Quantitys")
                        .HasColumnType("integer");

                    b.Property<string>("Dressing")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("boolean");

                    b.ToTable("Accessorys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Салат Цезар з куркою",
                            IsAvailable = true,
                            Name = "Цезар",
                            Price = 120.0,
                            Quantitys = 350,
                            Dressing = "Соус Цезар",
                            Ingredients = "Салат айсберг, курка, сир пармезан, крутони",
                            IsVegetarian = false
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Традиційний грецький салат",
                            IsAvailable = true,
                            Name = "Грецький салат",
                            Price = 95.0,
                            Quantitys = 180,
                            Dressing = "Оливкова олія",
                            Ingredients = "Огірки, томати, фета, оливки, цибуля",
                            IsVegetarian = true
                        });
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.CustomerProfileModel", b =>
                {
                    b.HasOne("ZooShop.Infrastructure.Models.CustomerModel", "Customer")
                        .WithOne("Profile")
                        .HasForeignKey("ZooShop.Infrastructure.Models.CustomerProfileModel", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.OrderProductModel", b =>
                {
                    b.HasOne("ZooShop.Infrastructure.Models.ProductModel", "Product")
                        .WithMany("OrderProductes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZooShop.Infrastructure.Models.OrderModel", "Order")
                        .WithMany("OrderProductes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.OrderModel", b =>
                {
                    b.HasOne("ZooShop.Infrastructure.Models.CustomerModel", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.PetFoodModel", b =>
                {
                    b.HasOne("ZooShop.Infrastructure.Models.ProductModel", null)
                        .WithOne()
                        .HasForeignKey("ZooShop.Infrastructure.Models.PetFoodModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.AccessoryModel", b =>
                {
                    b.HasOne("ZooShop.Infrastructure.Models.ProductModel", null)
                        .WithOne()
                        .HasForeignKey("ZooShop.Infrastructure.Models.AccessoryModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.ProductModel", b =>
                {
                    b.Navigation("OrderProductes");
                });

            modelBuilder.Entity("ZooShop.Infrastructure.Models.OrderModel", b =>
                {
                    b.Navigation("OrderProductes");
                });
#pragma warning restore 612, 618
        }
    }
}
